# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: 'npm_install'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        ls -R ../
        cd src
        npm install
        npm build
        ls -R ../
      displayName: 'npm install and build'

- stage: Test
  jobs:
  - job: 'npm_test'
    steps:
    - script: |
        ls -a
        npm test
    displayName: 'npm run test'
