# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true

variables:
  - template: azure-pipeline/vars/variables.yaml
    parameters:
      isTest: ${{ variables['Build.SourceBranch'] }}

pool:
  vmImage: ubuntu-latest
  uiSource: /src

stages:
  - template: azure-pipeline/stages/build-stage.yaml
  - template: azure-pipeline/stages/deploy-dev.yaml
  - template: azure-pipeline/stages/deploy-uat.yaml
