# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  nodeModules: $(System.DefaultWorkingDirectory)/**/node_modules

pool:
  vmImage: ubuntu-latest
  uiSource: /src

stages:
- stage: Build
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: 'npm_install'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - task: Cache@2
      inputs:
        key: '"npm" | "$(Agent.OS)" | src/package-lock.json'
        path: '$(nodeModules)'
        cacheHitVar: 'cachehit'
      displayName: 'cache node_modules'

    - script: |
        pushd $(uiSource)
        npm install
        npm run build
      displayName: 'npm install and build'


- stage: Test
  jobs:
  - job: 'npm_test'
    steps:
    - checkout: self
      clean: false
    - script: |
        npm test
      workingDirectory: src
    displayName: 'npm run test'
