stages:
  - stage: Deploy_UAT
    condition: and(not(failed('Build_and_Test'), eq(variables.isUAT, 'true'), eq(variables.isNightly, 'false'))
    displayName: "deploy to UAT"
    pool:
      vmImage: ubuntu-latest
    jobs:
      - template: ../jobs/deployUAT_job.yaml
