stages:
  - stage: Deploy_Prod
    condition: and(not(failed('Build_and_Test'), eq(variables.isMaster, 'true'), eq(variables.isNightly, 'false'))
    displayName: "deploy to Prod"
    pool:
      vmImage: ubuntu-latest
    jobs:
      - template: ../jobs/deployProd_job.yaml
