stages:
  - stage: Deploy_Dev
    condition: and(not(failed('Build_and_Test'), eq(variables.isDev, 'true'), eq(variables.isNightly, 'false'))
    displayName: "deploy to dev"
    pool:
      vmImage: ubuntu-latest
    jobs:
      - template: ../jobs/deployDev_job.yaml
