stages:
  - stage: Deploy_UAT
    condition: and(succeeded(), eq(variables.isUAT, 'true'), eq(variables.isNightly, 'false'))
    displayName: "deploy to UAT"
    pool:
      vmImage: ubuntu-latest
    jobs:
      - deployment: "deploy_to_uat"
        environment: "uat-env"
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: "Azure subscription 1(3adc070f-9710-4754-8588-55bbc2ae1644)"
                    appType: "webAppLinux"
                    appName: "test-mywebapp-react"
                    package: "$(Pipeline.Workspace)/drop/*.zip"
                    runtimeStack: "NODE|16-lts"
                    startUpCommand: "npm install -g serve && serve -s build"
